package Practica5;
import java.text.DecimalFormat;

/**
 * @author Gabriel
 * Esta es la clase PanelVisualizarSeguros (Interfaz)
 */
public class PanelVisualizarSeguros extends javax.swing.JPanel {
    /**Esta es una asociacion de la clase SeguroDeVida con la clase PanelVisualizarSeguros*/
    SeguroDeVida sv;
    /**Esta es una asociacion de la clase SeguroDeAuto con la clase PanelVisualizarSeguros*/
    SeguroDeAuto sa;
    /**Este es el atributo formato de tipo DecimalFormat*/
    DecimalFormat formato;
    
    /** Creates new form PanelVisualizarSeguros
     * Este es el constructor de la clase
     */
    public PanelVisualizarSeguros() {
        sv = new SeguroDeVida();
        sa = new SeguroDeAuto();
        formato = new DecimalFormat("#.##");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerSV = new javax.swing.JButton();
        btnVerSA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMAVida = new javax.swing.JTextField();
        txtPMVida = new javax.swing.JTextField();
        txtTotalMA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMAAuto = new javax.swing.JTextField();
        txtPMAuto = new javax.swing.JTextField();
        btnObtenerDatos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotalPM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        btnVerSV.setText("Visualizar Seguros de Vida");
        btnVerSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSVActionPerformed(evt);
            }
        });

        btnVerSA.setText("Visualizar Seguros de Auto");
        btnVerSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSAActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Monto Asegurado:");

        jLabel2.setText("Total Pago Mensual:");

        txtMAVida.setEnabled(false);

        txtPMVida.setEnabled(false);

        txtTotalMA.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel4.setText("Seguro de Vida");

        jLabel6.setText("Total Monto Asegurado:");

        jLabel7.setText("Total Pago Mensual:");

        txtMAAuto.setEnabled(false);

        txtPMAuto.setEnabled(false);

        btnObtenerDatos.setText("Obtener datos");
        btnObtenerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerDatosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel8.setText("Seguro de auto");

        txtTotalPM.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        jLabel9.setText("de los dos seguros");

        jLabel10.setText("Total Monto Asegurado:");

        jLabel11.setText("Total Pago Mensual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMAVida, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtPMVida)
                            .addComponent(txtPMAuto, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtMAAuto)
                            .addComponent(txtTotalMA, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtTotalPM)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnVerSV)
                        .addGap(43, 43, 43)
                        .addComponent(btnVerSA)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnObtenerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAVida))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPMVida))
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMAAuto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPMAuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerSV)
                    .addComponent(btnVerSA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObtenerDatos)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se encarga de ver todos los seguros de vida
     * @param evt 
     */
    private void btnVerSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSVActionPerformed
        sv.leerDeArchivo(); sv.ListarDatos();
    }//GEN-LAST:event_btnVerSVActionPerformed

    /**
     * Este metodo se encarga de ver todos los seguros de auto
     * @param evt 
     */
    private void btnVerSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSAActionPerformed
        sa.leerDeArchivo(); sa.listarDatos();
    }//GEN-LAST:event_btnVerSAActionPerformed

    /**
     * Este metodo se encarga de obtener la suma total de los montos asegurados y los pagos mensuales
     * @param evt 
     */
    private void btnObtenerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerDatosActionPerformed
        sv.leerDeArchivo(); sa.leerDeArchivo();
        double totalMAVida, totalPMVida, totalMAAuto, totalPMAuto;
        totalMAVida = totalPMVida = totalMAAuto = totalPMAuto = 0;
        for(Object Elementos : sv.listaSeguroV) {
            sv = (SeguroDeVida) Elementos;            
            totalMAVida += sv.getMontoAsegurado();
            totalPMVida += sv.getMontoPagoMensual();
        }        
        for(Object Elementos : sa.listaSeguroAuto) {
            sa = (SeguroDeAuto) Elementos;
            totalMAAuto += sa.getMontoAsegurado();
            totalPMAuto += sa.getMontoPagoMensual();
        }        
        txtMAVida.setText(String.valueOf(totalMAVida));
        txtPMVida.setText(String.valueOf(totalPMVida));
        txtMAAuto.setText(String.valueOf(totalMAAuto));
        txtPMAuto.setText(String.valueOf(formato.format(totalPMAuto)));
        txtTotalMA.setText(String.valueOf(totalMAVida + totalMAAuto));
        txtTotalPM.setText(String.valueOf(formato.format(totalPMVida + totalPMAuto)));
    }//GEN-LAST:event_btnObtenerDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObtenerDatos;
    private javax.swing.JButton btnVerSA;
    private javax.swing.JButton btnVerSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMAAuto;
    private javax.swing.JTextField txtMAVida;
    private javax.swing.JTextField txtPMAuto;
    private javax.swing.JTextField txtPMVida;
    private javax.swing.JTextField txtTotalMA;
    private javax.swing.JTextField txtTotalPM;
    // End of variables declaration//GEN-END:variables

}
