package Practica5;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
    
/**
 * @author Gabriel
 * Esta es la clase PanelSeguroAuto (Interfaz)
 */
public class PanelSeguroAuto extends javax.swing.JPanel {
    /**Este es el atributo color de tipo Color*/
    Color color;
    /**Esta es una asociacion de la clase SeguroDeAuto con la clase PanelSeguroDeAuto*/
    SeguroDeAuto sa;

    /**
     * Creates new form PanelSeguroAuto
     * Este es el constructor de la clase PanelSeguroAuto
     */
    public PanelSeguroAuto() {
        sa = new SeguroDeAuto();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        ComboCovertura = new javax.swing.JComboBox<>();
        txtMontoAsegurado = new javax.swing.JTextField();
        txtPagoMensual = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLeerDeArchivo = new javax.swing.JButton();
        btnSeleccionarColor = new javax.swing.JButton();
        btnBuscarSeguro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarSeguro = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel1.setText("SEGURO DE AUTO");

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Placa: (A-000-AAA)");

        jLabel5.setText("Color:");

        jLabel6.setText("Covetura:");

        jLabel7.setText("Monto Asegurado:");

        jLabel8.setText("Pago Mensual:");

        ComboCovertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amplia", "Limitada" }));

        txtPagoMensual.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLeerDeArchivo.setText("Leer Archivo");
        btnLeerDeArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerDeArchivoActionPerformed(evt);
            }
        });

        btnSeleccionarColor.setText("Selecciona color");
        btnSeleccionarColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarColorActionPerformed(evt);
            }
        });

        btnBuscarSeguro.setText("Buscar seguro");
        btnBuscarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSeguroActionPerformed(evt);
            }
        });

        jLabel9.setText("Ingresar placa:");

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel10.setText("Buscar Seguro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLeerDeArchivo)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnBuscarSeguro))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBuscarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMarca)
                                        .addComponent(txtModelo)
                                        .addComponent(txtPlaca)
                                        .addComponent(ComboCovertura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMontoAsegurado)
                                        .addComponent(btnSeleccionarColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPagoMensual, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarColor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboCovertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMontoAsegurado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBuscarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLeerDeArchivo)
                    .addComponent(btnBuscarSeguro))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se encarga de seleccionar el color del carro
     * @param evt 
     */
    private void btnSeleccionarColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarColorActionPerformed
        color = JColorChooser.showDialog(null, "Seleccione un Color", Color.BLUE);
        sa.setColor(color);
        btnSeleccionarColor.setBackground(color);        
    }//GEN-LAST:event_btnSeleccionarColorActionPerformed

    /**
     * Este metodo se encarga de agregar losdatos del asegurado en un archivo binario
     * @param evt 
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        sa.leerDeArchivo();
        sa.setMarca(txtMarca.getText());
        sa.setModelo(Integer.parseInt(txtModelo.getText()));
        sa.setPlaca(txtPlaca.getText());        
        sa.setTipoCovertura(ComboCovertura.getItemAt(ComboCovertura.getSelectedIndex()));
        sa.setMontoAsegurado(Double.parseDouble(txtMontoAsegurado.getText()));
        double pago = sa.calcularPagoMensual();
        sa.setMontoPagoMensual(pago);
        txtPagoMensual.setText(String.valueOf(pago));
        sa.listaSeguroAuto.add(sa);
        sa.imprimirEnArchivo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Este metodo se encarga de leer los datos del archivo
     * @param evt 
     */
    private void btnLeerDeArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerDeArchivoActionPerformed
        sa.leerDeArchivo();
        JOptionPane.showMessageDialog(null, "Marca: " + sa.getMarca() + "\nModelo: " + sa.getModelo() +
                "\nPlaca: " + sa.getPlaca() + "\nColor: " + sa.getColor() + "\nCovertura: " + sa.getTipoCovertura() +
                "\nMonto Asegurado: " + sa.getMontoAsegurado() + "\nPago Mensual: " + sa.getMontoPagoMensual());       
    }//GEN-LAST:event_btnLeerDeArchivoActionPerformed

    /**
     * Este metodo se encarga de buscar un seguro ya existente
     * @param evt 
     */
    private void btnBuscarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSeguroActionPerformed
        String placa = txtBuscarSeguro.getText();
        int x = 1;
        sa.leerDeArchivo();  
        for(Object Elementos : sa.listaSeguroAuto) {
            sa = (SeguroDeAuto) Elementos;
            if(placa == null ? sa.getPlaca() == null : placa.equals(sa.getPlaca())) { // operador terneario
                JOptionPane.showMessageDialog(null, "Marca: " + sa.getMarca() + "\nModelo: " + sa.getModelo() +
                "\nPlaca: " + sa.getPlaca() + "\nColor: " + sa.getColor() + "\nCovertura: " + sa.getTipoCovertura() +
                "\nMonto Asegurado: " + sa.getMontoAsegurado() + "\nPago Mensual: " + sa.getMontoPagoMensual());   
                x = 1;
                break;
            }
            else {
                x = 0;
            }
        }
        if(x == 0) {
            JOptionPane.showMessageDialog(null, "No existe");
        }
    }//GEN-LAST:event_btnBuscarSeguroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCovertura;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarSeguro;
    private javax.swing.JButton btnLeerDeArchivo;
    private javax.swing.JButton btnSeleccionarColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBuscarSeguro;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMontoAsegurado;
    private javax.swing.JTextField txtPagoMensual;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
