package Practica5;
import javax.swing.JOptionPane;

/**
 * @author Gabriel
 * Esta es la clase PanelSeguroVida (Interfaz)
 */
public class PanelSeguroVida extends javax.swing.JPanel {
    /**Esta es una asociación de la clase SeguroDeVida con la clase PanelSeguroDeVida*/
    SeguroDeVida sv;        
    
    /**
     * Creates new form PanelSeguroVida
     * Este es el constructor de la clase PanelSeguroDeVida
     */
    public PanelSeguroVida() {
        sv = new SeguroDeVida();        
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboCovertura = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtMontoAsegurado = new javax.swing.JTextField();
        txtPagoMensual = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLeerDeArchivo = new javax.swing.JButton();
        btnBuscarSeguro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscarSeguro = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(420, 390));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel1.setText("SEGURO DE VIDA");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        jLabel4.setText("Covertura:");

        jLabel5.setText("Monto Asegurado:");

        jLabel6.setText("Pago Mensual:");

        ComboCovertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amplia", "Limitada" }));

        txtPagoMensual.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLeerDeArchivo.setText("Leer archivo");
        btnLeerDeArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerDeArchivoActionPerformed(evt);
            }
        });

        btnBuscarSeguro.setText("Buscar seguro");
        btnBuscarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSeguroActionPerformed(evt);
            }
        });

        jLabel7.setText("Ingresar nombre: ");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel8.setText("Buscar Seguro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLeerDeArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnBuscarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(ComboCovertura, 0, 98, Short.MAX_VALUE)
                            .addComponent(txtMontoAsegurado, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtPagoMensual, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txtBuscarSeguro))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(165, 165, 165))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCovertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoAsegurado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscarSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLeerDeArchivo)
                    .addComponent(btnBuscarSeguro))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se encarga de agregar los datos a un archivo binario
     * @param evt 
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        sv.leerDeArchivo();
        sv.setNombreAsegurado(txtNombre.getText());
        sv.setEdad(Integer.parseInt(txtEdad.getText()));
        sv.setTipoCovertura(ComboCovertura.getItemAt(ComboCovertura.getSelectedIndex()));
        sv.setMontoAsegurado(Double.parseDouble(txtMontoAsegurado.getText()));
        double pago = sv.calcularPagoMensual(); 
        sv.setMontoPagoMensual(pago);
        txtPagoMensual.setText(String.valueOf(sv.getMontoPagoMensual()));
        sv.listaSeguroV.add(sv);        
        sv.imprimirEnArchivo();       
                
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Este metodo se encarga de leer los datos del archivo
     * @param evt 
     */
    private void btnLeerDeArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerDeArchivoActionPerformed
        sv.leerDeArchivo();        
        JOptionPane.showMessageDialog(null, "Nombre: " + sv.getNombreAsegurado() + "\nEdad: "
            + sv.getEdad() + "\nMonto asegurado: " + sv.getMontoAsegurado() +
                    "\nPago mensual: " + sv.getMontoPagoMensual());
    }//GEN-LAST:event_btnLeerDeArchivoActionPerformed

    /**
     * Este metodo se encarga de buscar un seguro ya existente
     * @param evt 
     */
    private void btnBuscarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSeguroActionPerformed
        String nombre = txtBuscarSeguro.getText();
        int x = 1;
        sv.leerDeArchivo();  
        for(Object Elementos : sv.listaSeguroV) {
            sv = (SeguroDeVida) Elementos;
            if(nombre == null ? sv.getNombreAsegurado() == null : nombre.equals(sv.getNombreAsegurado())) { // operador terneario
                JOptionPane.showMessageDialog(null, "Nombre: " + sv.getNombreAsegurado() + "\nEdad: "
                 + sv.getEdad() + "\nMonto asegurado: " + sv.getMontoAsegurado() +
                    "\nPago mensual: " + sv.getMontoPagoMensual());
                x = 1;
                break;
            }
            else {
                x = 0;
            }
        }        
        if(x == 0) {
            JOptionPane.showMessageDialog(null, "No existe");
        }
  
    }//GEN-LAST:event_btnBuscarSeguroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCovertura;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarSeguro;
    private javax.swing.JButton btnLeerDeArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtBuscarSeguro;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMontoAsegurado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPagoMensual;
    // End of variables declaration//GEN-END:variables
}
