package Practica4;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author GABRIEL LÓPEZ AGUIRRE    
 * Esta es la clase CasaDeEmpeño. Aqui se hace la interfaz grafica
 */
public class CasaDeEmpeño extends javax.swing.JFrame {
    /**Este es el atributo modeloDeEnum*/
    ComboBoxModel modeloDeEnum;
    /**Este es el atributo ModeloClientes*/
    DefaultListModel ModeloClientes;
    /**Este es el atributo ModeloPrendas*/
    DefaultListModel ModeloPrendas;
    /**Este es el atributo listaCliente*/
    private ArrayList listaCliente;
    /**Este es el atributo listaPrenda*/
    private ArrayList listaPrenda;
    /**Este es el atributo numClientesRegistrados*/
    private int numClientesRegistrados;
    /**Este es el atributo numPrendasIngresadas*/
    private int numPrendasIngresadas;
    /**Este es el atributo totalTDI (totalTasaDeInteres)*/
    private double totalTDI;
    /**Este es el atributo formato*/
    DecimalFormat formato = new DecimalFormat("#.##");
    
    
    /**
     * Creates new form CasaDeEmpeño
     * Este es el constructor de la clase CasaDeEmpeño
     */
    public CasaDeEmpeño() {
        modeloDeEnum = new DefaultComboBoxModel(Categoria.values());
        ModeloClientes = new DefaultListModel();
        ModeloPrendas = new DefaultListModel();
        listaCliente = new ArrayList<>(10);
        listaPrenda = new ArrayList<>(20);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lClientes = new javax.swing.JList<>();
        tabPrendas = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        btnEmpeñar = new javax.swing.JButton();
        btnRegresarPrenda = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLMontoPrestado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lPrendasEnCasa = new javax.swing.JList<>();
        txtFecha = new javax.swing.JTextField();
        txtValorComercial = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTipoDePrenda = new javax.swing.JTextField();
        tabGanancias = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLNumClientes = new javax.swing.JLabel();
        jLNumEmpeños = new javax.swing.JLabel();
        jLGanancias = new javax.swing.JLabel();
        btnGanancias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa de Empeño");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Telefono:");

        jLabel3.setText("Saldo:");

        txtSaldo.setText("0");
        txtSaldo.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lClientes.setModel(ModeloClientes);
        lClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lClientes);

        javax.swing.GroupLayout tabClientesLayout = new javax.swing.GroupLayout(tabClientes);
        tabClientes.setLayout(tabClientesLayout);
        tabClientesLayout.setHorizontalGroup(
            tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClientesLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        tabClientesLayout.setVerticalGroup(
            tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabClientesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabClientesLayout.createSequentialGroup()
                        .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(tabClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(btnAgregar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", tabClientes);

        jComboBox1.setModel(modeloDeEnum);

        jLabel5.setText("Cliente:");

        jLabel6.setText("Fecha de ingreso:  (dd/mm/aaaa)");

        jLabel7.setText("Valor comercial:");

        btnEmpeñar.setText("Empeñar");
        btnEmpeñar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpeñarActionPerformed(evt);
            }
        });

        btnRegresarPrenda.setText("Regresar prenda");
        btnRegresarPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPrendaActionPerformed(evt);
            }
        });

        jLabel12.setText("Monto prestado:");

        jLMontoPrestado.setEnabled(false);

        lPrendasEnCasa.setModel(ModeloPrendas);
        lPrendasEnCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPrendasEnCasaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lPrendasEnCasa);

        jLabel16.setText("Descripción:");

        jLabel8.setText("Tipo de prenda:");

        javax.swing.GroupLayout tabPrendasLayout = new javax.swing.GroupLayout(tabPrendas);
        tabPrendas.setLayout(tabPrendasLayout);
        tabPrendasLayout.setHorizontalGroup(
            tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrendasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabPrendasLayout.createSequentialGroup()
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresarPrenda))
                        .addGap(18, 18, 18)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha)
                            .addComponent(txtValorComercial)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(btnEmpeñar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoDePrenda)
                            .addComponent(jLMontoPrestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        tabPrendasLayout.setVerticalGroup(
            tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrendasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPrendasLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTipoDePrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMontoPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPrenda)
                    .addComponent(btnEmpeñar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prendas", tabPrendas);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("N° de clientes:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("N° de empeños:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ganancias:");

        jLNumClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNumClientes.setText("0");

        jLNumEmpeños.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNumEmpeños.setText("0");

        jLGanancias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGanancias.setText("Obtener ganancias");
        btnGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGananciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabGananciasLayout = new javax.swing.GroupLayout(tabGanancias);
        tabGanancias.setLayout(tabGananciasLayout);
        tabGananciasLayout.setHorizontalGroup(
            tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGananciasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGanancias)
                    .addGroup(tabGananciasLayout.createSequentialGroup()
                        .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLNumClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLNumEmpeños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        tabGananciasLayout.setVerticalGroup(
            tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabGananciasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLNumClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLNumEmpeños, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(tabGananciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnGanancias)
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Ganancias", tabGanancias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este es el metodo que agrega clientes a la lista grafica
     * @param evt 
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        Cliente c = new Cliente(txtNombre.getText(), Integer.parseInt(txtTelefono.getText()));
        listaCliente.add(c);
        ModeloClientes.addElement(c);
        numClientesRegistrados++;
        jLNumClientes.setText(String.valueOf(numClientesRegistrados));
    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     * Este es el metodo que nos permite seleccionar clientes de la lista grafica
     * @param evt 
     */
    private void lClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lClientesMouseClicked
        int seleccion = lClientes.getSelectedIndex();
        Cliente c = (Cliente) listaCliente.get(seleccion);         
        txtNombre.setText(c.getNombre());
        jLCliente.setText(c.getNombre());
        txtTelefono.setText(String.valueOf(c.getTelefono()));
        txtSaldo.setText(String.valueOf(c.getSaldo()));          
    }//GEN-LAST:event_lClientesMouseClicked
    /**
     * Este es el metodo que agrega prendas a la lista grafica ModeloPrendas
     * @param evt 
     */
    private void btnEmpeñarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpeñarActionPerformed
        
        if(lClientes.isSelectionEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Seleccione a un cliente");
        }
        else {
            Fecha f = new Fecha(txtFecha.getText());
            Cliente c = new Cliente(txtNombre.getText(), Integer.parseInt(txtTelefono.getText()));
            double MontoPrestado = Double.parseDouble(txtValorComercial.getText()) * .6;
            Prenda p = new Prenda(txtDescripcion.getText(), txtTipoDePrenda.getText(),
                Double.parseDouble(txtValorComercial.getText()), MontoPrestado, f, c);            
            listaPrenda.add(p);
            ModeloPrendas.addElement(p);
            String MP = String.valueOf(MontoPrestado);        
            jLMontoPrestado.setText(MP);     
            numPrendasIngresadas++;
            jLNumEmpeños.setText(String.valueOf(numPrendasIngresadas)); 
        }
    }//GEN-LAST:event_btnEmpeñarActionPerformed
    /**
     * Este es el metodo que elimina prendas de la lista grafica ModeloPrendas
     * @param evt 
     */
    private void btnRegresarPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPrendaActionPerformed
        Fecha f = new Fecha(txtFecha.getText());                
        int seleccion = lPrendasEnCasa.getSelectedIndex();
        double TasaDeInteres = f.calcularTasaDeInteres(Double.parseDouble(txtValorComercial.getText()),
                Double.parseDouble(jLMontoPrestado.getText()), f.getFechaI());
        int op = JOptionPane.showConfirmDialog(null, "¿Desea pagar $"+ formato.format(TasaDeInteres)+ " por su prenda?");
        if(op == 0) {
            ModeloPrendas.remove(seleccion);  
            totalTDI += TasaDeInteres; 
        }    
    }//GEN-LAST:event_btnRegresarPrendaActionPerformed
    /**
     * Este es el metodo que nos permite seleccionar prendas de la lista grafica ModeloPrendas
     * @param evt 
     */
    private void lPrendasEnCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPrendasEnCasaMouseClicked
        int seleccion = lPrendasEnCasa.getSelectedIndex();
        Prenda p = (Prenda) ModeloPrendas.get(seleccion);  
        jLCliente.setText(p.getDueño().getNombre());
        txtTipoDePrenda.setText(p.getTipo());
        txtDescripcion.setText(p.getDescripcion());
        txtFecha.setText(p.getFecha().toString());
        txtValorComercial.setText(String.valueOf(p.getValorComercial()));
        jLMontoPrestado.setText(String.valueOf(p.getValorCliente()));
    }//GEN-LAST:event_lPrendasEnCasaMouseClicked
    /**
     * Este es el metodo que nos muestra las ganancias totales
     * @param evt 
     */
    private void btnGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGananciasActionPerformed

        double GananciaTotal = 0;
        double total = 0,total1 = 0;
        double valorComercial = 0, montoPrestado = 0;
        
        for(int i = 0 ; i<ModeloPrendas.size() ; i++) {              
            Prenda p = (Prenda) ModeloPrendas.get(i);            
            total += p.getValorComercial();        
            total1 += p.getValorCliente();
        }        
        
        valorComercial += total;
        montoPrestado += total1;
        GananciaTotal = totalTDI + valorComercial - montoPrestado;
        formato.format(GananciaTotal);
        jLGanancias.setText(formato.format(GananciaTotal));               
    }//GEN-LAST:event_btnGananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasaDeEmpeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasaDeEmpeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasaDeEmpeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasaDeEmpeño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaDeEmpeño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEmpeñar;
    private javax.swing.JButton btnGanancias;
    private javax.swing.JButton btnRegresarPrenda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLGanancias;
    private javax.swing.JLabel jLMontoPrestado;
    private javax.swing.JLabel jLNumClientes;
    private javax.swing.JLabel jLNumEmpeños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lClientes;
    private javax.swing.JList<String> lPrendasEnCasa;
    private javax.swing.JPanel tabClientes;
    private javax.swing.JPanel tabGanancias;
    private javax.swing.JPanel tabPrendas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoDePrenda;
    private javax.swing.JTextField txtValorComercial;
    // End of variables declaration//GEN-END:variables
}
